
title: 		Slide Template
description:
#Comment out url when working locally to resolve base urls correctly ok
#use this when pushing to git for live version

# url:      http://lwasser.github.io
# baseurl:	http://lwasser.github.io

# use this when working locally
url: http://localhost:4000
# baseurl: http://localhost:4000
