# This should be the repo name WITHOUT the host
baseurl: /hide-yo-jekyll

# Format for the slides, can be either 16:9 or 4:3
format: '4:3'

# Collections
collections:
  - lessons

defaults:
  - scope:
      collection: lessons
    values:
      layout: slides
